Project_MVC/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;
using System.Web.Mvc;

namespace Project_MVC.Controllers
{
    public class WriterPanelContentController : Controller
    {
        // GET: WriterPanelContent
        ContentManager cm = new ContentManager(new EfContentDal());
        WriterManager wm = new WriterManager(new EfWriterDal());

        public ActionResult MyContent(string p)
        {
            int id;
            p = (string)Session["Writermail"];
            var writerinfo = wm.GetByMail(p);
            id = writerinfo.WriterId;
            var value = cm.GetListByWriterId(id);
            return View(value);

        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        } 
        [HttpPost]
        public ActionResult AddContent(Content p)
        {

            var mail = (string)Session["Writermail"];
            var writerinfo = wm.GetByMail(mail);

            p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterId=writerinfo.WriterId;
            p.ContentStatus = true;
            cm.ContentAdd(p);
            return View("MyContent");
        }
    }
}

Project_MVC/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>İçeriğe Giriş</h2>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
<div class="form-group">
    
    
    <input type="hidden" name="HeadingId" value="@ViewBag.d" />
    <br />
    @Html.Label("İçeriği Yazınız")
    @Html.TextAreaFor(x => x.ContentValue, 4, 10, new { @class = "form-control" })

    <br />
    <button class="btn btn-info">Kaydet</button>

</div>
}

Project_MVC/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>

@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {


                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#"> @item.Writer.WriterName @item.Writer.WriterSurname</a></h3>
                                        <h3 class="timeline-header"><b>@item.Heading.HeadingName</b> </h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>