Project_MVC/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using EntityLayer.EDto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Project_MVC.Controllers
{
    public class AuthorizationsController : Controller
    {
       
       
            // GET: Authorization
            AdminManager adm = new AdminManager(new EfAdminDal());
            AdminRoleManager admRole = new AdminRoleManager(new EfAdminRoleDal());
            Context context = new Context();

        public ActionResult Index()
            {
                var adminvalues = adm.GetList();
                return View(adminvalues);
            }
            [HttpGet]
            public ActionResult NewAdmin()
            {
                
                List<SelectListItem> valueRole = (from x in admRole.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.RoleName.ToString(),
                                                      Value = x.RoleName
                                                  }).ToList();
                ViewBag.dgr1 = valueRole;
                
                return View();
              
            }
            [HttpPost]
            public ActionResult NewAdmin(string mail,AdminForRegisterDto c)
            {
            
                Session["EMail"] = c.Mail.ToString();

           
                if (context.Admines.Where(x => x.Mail == mail).Any())
                {
                    ViewBag.Mesaj = "Bu mail adresiyle daha önce kayıt yapıldı.";
                    return View("NewAdmin");
                }
                else
                {
                                  
                    adm.AdminAdd(c, c.Password);                  
                                   
                return RedirectToAction("Index");
                }
            }
        //private void SendActivationEmail(Manager manager, AdminForRegisterDto c)
        //{
        //    string p = (string)Session["EMail"];
        //    manager.Mail = p;
           

        //    using (MailMessage mm = new MailMessage("bertictest@gmail.com", c.Mail))
        //    {
        //        mm.Subject = "Hesap Aktivasyonu";
        //        string body = "Merhaba " + c.UserName + ",";
        //        body += "<br /><br />Hesabınızı etkinleştirmek için lütfen aşağıdaki bağlantıyı tıklayın";
        //        body += "<br /><a href = '" + string.Format("{0}://{1}/Authorizations/Confirmation/{2}", Request.Url.Scheme, Request.Url.Authority, manager.Admin_Confirmation_Code1 +manager.Admin_Confirmation_Code2 )+ "'>Hesabınızı etkinleştirmek için burayı tıklayın.</a>";
        //        body += "<br /><br />Teşekkürler";
        //        mm.Body = body;
        //        mm.IsBodyHtml = true;
        //        SmtpClient smtp = new SmtpClient();
        //        smtp.Host = "smtp.gmail.com";
        //        smtp.EnableSsl = true;
        //        NetworkCredential NetworkCred = new NetworkCredential("bertictest@gmail.com", "147896325a.s");
        //        smtp.UseDefaultCredentials = true;
        //        smtp.Credentials = NetworkCred;
        //        smtp.Port = 587;
        //        smtp.Send(mm);
        //    }
        //}

       
        [HttpGet]
            public ActionResult ChangeRole(int id)
            {
                List<SelectListItem> valueRole = (from x in admRole.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.RoleName.ToString(),
                                                      Value = x.RoleName
                                                  }).ToList();
                ViewBag.dgr1 = valueRole;
                var value = adm.GetById(id);
                return View(value);
            }
            [HttpPost]
            public ActionResult ChangeRole(Manager manager)
            {

                adm.ChangeRole(manager.Id, manager.Role);
                return RedirectToAction("Index");
            }
            public ActionResult FalseStatusAdmin(int id)
            {
                var value = adm.GetById(id);
                value.Status = false;
                adm.AdminUpdate(value);              
                return RedirectToAction("Index");
        }
        public ActionResult TrueStatusAdmin(int id)
        {
            var value = adm.GetById(id);
            value.Status = true;
            adm.AdminUpdate(value);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAdmin(int id)
        {
            var value = adm.GetById(id);        
            adm.AdminDelete(value);
            return RedirectToAction("Index");
        }
    }

}

Project_MVC/Views/Authorizations/ChangeRole.cshtml
@model EntityLayer.Concrete.Manager
@{
    ViewBag.Title = "ChangeRole";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using (Html.BeginForm("ChangeRole", "Authorizations", FormMethod.Post))
{
<div class="form-group">

    <br /><br />
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })

    @Html.Label("Admin Ad")
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.Label("Admin Mail")
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />
    @*@Html.Label("Admin Rolü")    
    @Html.DropDownListFor(x => x.Role, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />*@
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

Project_MVC/Views/Authorizations/Index.cshtml
@using EntityLayer.Concrete
@model List<Manager>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        @*<th>Yetki</th>*@
        <th>Durum</th>
        <th>Pasif Yap</th>
        <th>Aktif Yap</th>
        <th>Sil</th>
        <th>Güncelle</th>


    </tr>
    @foreach (var item in Model)
    {
<tr>
    <th>@item.Id</th>
    <td>@item.Mail</td>
    @*<td>@item.Role</td>*@
    <td>@item.Status</td>
    <td><a href="/Authorizations/FalseStatusAdmin/@item.Id" class="btn btn-primary">Pasif Yap</a></td>
    <td><a href="/Authorizations/TrueStatusAdmin/@item.Id" class="btn btn-success">Aktif Yap </a></td>
    <td><a href="/Authorizations/DeleteAdmin/@item.Id" class="btn btn-danger">Sil</a></td>
    <td><a href="/Authorizations/ChangeRole/@item.Id" class="btn btn-warning">Güncelle</a></td>
</tr>
    }
</table>

<br />

<a href="/Authorizations/NewAdmin" class="btn btn-info">Yeni Admin Tanımla</a>

Project_MVC/Views/Authorizations/NewAdmin.cshtml
@model EntityLayer.EDto.AdminForRegisterDto

@{
    ViewBag.Title = "NewAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("NewAdmin", "Authorizations", FormMethod.Post))
{
<div class="form-group">
    @*<tr>
        <td colspan="3" class="renk ">@ViewBag.Mesaj</td>
    </tr>*@
    <br />
    @Html.Label("Admin Adı")
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @*@Html.Label("Admin Rolü")
    @Html.DropDownListFor(x => x.Id, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />*@
    @Html.Label("Admin Mail")
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />
    @Html.Label("Admin Password")
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <br />
    <br />
    <button id="btn3" class="btn btn-danger">Kaydet</button>
</div>
}